PMN adds a new const char* signature
From: moosusers-request@lists.csail.mit.edu   Original Message

From: moosusers-request@lists.csail.mit.edu
Subject: Moosusers Digest, Vol 71, Issue 7
Date: 26 April 2012 17:00:09 GMT+01:00
To: moosusers@lists.csail.mit.edu
Reply-To: moosusers@lists.csail.mit.edu

Send Moosusers mailing list submissions to
	moosusers@lists.csail.mit.edu

To subscribe or unsubscribe via the World Wide Web, visit
	https://lists.csail.mit.edu/mailman/listinfo/moosusers
or, via email, send a message with subject or body 'help' to
	moosusers-request@lists.csail.mit.edu

You can reach the person managing the list at
	moosusers-owner@lists.csail.mit.edu

When replying, please edit your Subject line so it is more specific
than "Re: Contents of Moosusers digest..."

Today's Topics:

  1. Re: Moosusers Digest, Vol 71, Issue 5 (Thepmn)

----------------------------------------------------------------------

Message: 1
Date: Tue, 24 Apr 2012 17:02:26 +0100
From: Thepmn <thepmn@googlemail.com>
To: "moosusers@lists.csail.mit.edu" <moosusers@lists.csail.mit.edu>
Subject: Re: [Moosusers] Moosusers Digest, Vol 71, Issue 5
Message-ID: <B8E53462-6652-4EBE-B144-AB4B985D115B@googlemail.com>
Content-Type: text/plain;	charset=us-ascii

We'll
Fix this. Apologies.

Sent from a phone. Forgive typng  mistakes.

On 24 Apr 2012, at 17:00, moosusers-request@lists.csail.mit.edu wrote:

Send Moosusers mailing list submissions to
  moosusers@lists.csail.mit.edu

To subscribe or unsubscribe via the World Wide Web, visit
  https://lists.csail.mit.edu/mailman/listinfo/moosusers
or, via email, send a message with subject or body 'help' to
  moosusers-request@lists.csail.mit.edu

You can reach the person managing the list at
  moosusers-owner@lists.csail.mit.edu

When replying, please edit your Subject line so it is more specific
than "Re: Contents of Moosusers digest..."

Today's Topics:

 1. Notify() Overloads Have Similar Conversion
    (Sideleau, Scott R CIV NUWC NWPT)
 2. Re: Notify() Overloads Have Similar Conversion (toby schneider)

----------------------------------------------------------------------

Message: 1
Date: Mon, 23 Apr 2012 18:37:11 -0400
From: "Sideleau, Scott R CIV NUWC NWPT" <scott.sideleau@navy.mil>
To: <moosusers@lists.csail.mit.edu>
Subject: [Moosusers] Notify() Overloads Have Similar Conversion
Message-ID:
  <D8D12C2E0FA97048A8A6D8A4AF71EE6A02A5122E@naeaphilez03v.nadsusea.nads.navy.mil>

Content-Type: text/plain; charset="us-ascii"

Hi all,

I received a report recently that compiling some MOOS applications (in this case, from the moos-ivp-iver tree) in Visual Studio 2010 on Windows resulted in the following compile time error from the use of CMOOSCommClient::Notify() to post to MOOSdb variables:

==================================================
D:\Sandbox\moos-ivp-iver\src\iOceanServerComms\iOceanServerComms.cpp(232): error C2666: 'CMOOSCommClient::Notify' : 2 overloads have similar conversions
2>          d:\sandbox\moos-ivp\moos-2375-oct0611-modified\core\mooslib\MOOSCommClient.h(91): could be 'bool CMOOSCommClient::Notify(const std::string &,void *,unsigned int,double)'
2>          d:\sandbox\moos-ivp\moos-2375-oct0611-modified\core\mooslib\MOOSCommClient.h(83): or       'bool CMOOSCommClient::Notify(const std::string &,const std::string &,double)'
==================================================

The error is kind of ugly to read, but the compiler is complaining about the two function signatures of Notify() in CMOOSCommClient being vague.  The user resolved the situation by explicitly declaring the content string of the posted-to MOOS variables as std::string type, but this bloats the code, in my opinion.

You end up going from...

m_Comms.Notify("MOOSDB_VARIABLE", "FOO", dfTimeNow);

...to...

std::string sTmp = "FOO";
m_Comms.Notify("MOOSDB_VARIABLE", sTmp, dfTimeNow);

...just to remove the compile time error on Windows.

Has anyone seen this Visual Studio compile time error before that has a better solution?

Thanks, in advance.
__________________________________________________
Scott R. Sideleau
Computer Systems & Software Engineer
NUWCDIVNPT Code 2511
Phone: (401) 832-3129
scott.sideleau@navy.mil

-------------- next part --------------
A non-text attachment was scrubbed...
Name: smime.p7s
Type: application/x-pkcs7-signature
Size: 5700 bytes
Desc: not available
URL: <https://lists.csail.mit.edu/mailman/private/moosusers/attachments/20120423/b70dcda8/attachment-0001.bin>

------------------------------

Message: 2
Date: Mon, 23 Apr 2012 20:06:34 -0400
From: toby schneider <tes@MIT.EDU>
To: moosusers@lists.csail.mit.edu
Subject: Re: [Moosusers] Notify() Overloads Have Similar Conversion
Message-ID: <4F95EE8A.3080308@mit.edu>
Content-Type: text/plain; charset=ISO-8859-1

Hi -

Best solution would be for MOOS to explicitly define

bool CMOOSCommClient::Notify(const std::string &,const char *,double);

Until that happens that you can save yourself the extra code by
explicitly calling the std::string(const char*) constructor:

m_Comms.Notify("MOOSDB_VARIABLE", std::string("FOO"), dfTimeNow);

-t

On 04/23/2012 06:37 PM, Sideleau, Scott R CIV NUWC NWPT wrote:
Hi all,

I received a report recently that compiling some MOOS applications (in this case, from the moos-ivp-iver tree) in Visual Studio 2010 on Windows resulted in the following compile time error from the use of CMOOSCommClient::Notify() to post to MOOSdb variables:

==================================================
D:\Sandbox\moos-ivp-iver\src\iOceanServerComms\iOceanServerComms.cpp(232): error C2666: 'CMOOSCommClient::Notify' : 2 overloads have similar conversions
2>          d:\sandbox\moos-ivp\moos-2375-oct0611-modified\core\mooslib\MOOSCommClient.h(91): could be 'bool CMOOSCommClient::Notify(const std::string &,void *,unsigned int,double)'
2>          d:\sandbox\moos-ivp\moos-2375-oct0611-modified\core\mooslib\MOOSCommClient.h(83): or       'bool CMOOSCommClient::Notify(const std::string &,const std::string &,double)'
==================================================

The error is kind of ugly to read, but the compiler is complaining about the two function signatures of Notify() in CMOOSCommClient being vague.  The user resolved the situation by explicitly declaring the content string of the posted-to MOOS variables as std::string type, but this bloats the code, in my opinion.

You end up going from...

m_Comms.Notify("MOOSDB_VARIABLE", "FOO", dfTimeNow);

...to...

std::string sTmp = "FOO";
m_Comms.Notify("MOOSDB_VARIABLE", sTmp, dfTimeNow);

...just to remove the compile time error on Windows.

Has anyone seen this Visual Studio compile time error before that has a better solution?

Thanks, in advance.
__________________________________________________
Scott R. Sideleau
Computer Systems & Software Engineer
NUWCDIVNPT Code 2511
Phone: (401) 832-3129
scott.sideleau@navy.mil

_______________________________________________
Moosusers mailing list
Moosusers@lists.csail.mit.edu
https://lists.csail.mit.edu/mailman/listinfo/moosusers

--
? toby schneider | tes@mit.edu ?
? mit/whoi joint program student in
   ocean engineering ?
? 1.508.444.2131 ?
? http://gobysoft.com ?

------------------------------

_______________________________________________
Moosusers mailing list
Moosusers@lists.csail.mit.edu
https://lists.csail.mit.edu/mailman/listinfo/moosusers

End of Moosusers Digest, Vol 71, Issue 5
****************************************

------------------------------

_______________________________________________
Moosusers mailing list
Moosusers@lists.csail.mit.edu
https://lists.csail.mit.edu/mailman/listinfo/moosusers

End of Moosusers Digest, Vol 71, Issue 7
*************************************

Signed-off-by: Paul Newman <pnewman@robots.ox.ac.uk>